version: '3.8'

services:
  app:
    restart: 'always'
    build: .
    ports:
      - 4500:4500
  mysql:
    image: mysql:8.0.19
    restart: 'always'
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
